site_name: "Open Quantum Design"
site_description: Open Quantum Design - the world's first open-source quantum computer

repo_name: OpenQuantumDesign/equilux
repo_url: https://github.com/OpenQuantumDesign/equilux.git

copyright: Copyright &copy; 2024-2025 Open Quantum Design

use_directory_urls: false

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/OpenQuantumDesign
      name: Open Quantum Design GitHub
    - icon: fontawesome/solid/globe
      link: https://openquantumdesign.org
      name: Open Quantum Design Website

nav:
  - Get Started:
      - Welcome: index.md
      - Installation: get-started.md

  - Tutorials:
      - Analog:
          - Analog Tutorials: tutorials/index.md
          - Rabi Flopping: tutorials/rabi-flopping.md
          - Ising Model: tutorials/ising.md
  - Examples:
      - Analog:
          - Rabi Flopping: examples/one_qubit_rabi_flopping.ipynb
          - Bell state preparation: examples/bell_state.ipynb
          - GHZ state preparation: examples/ghz_state.ipynb
          - Adiabatic state:
              - Linear time-dependence: examples/adiabatic_linear.ipynb
              - Sigmoid time-dependence: examples/adiabatic_sigmoid.ipynb
          - Ising model: examples/ising_model.ipynb
          - QAOA: examples/qaoa.ipynb
          - Quantum scars: examples/quantum_scars.ipynb

  - Core: "!include ./oqd-core/mkdocs.yaml"
  - Emulators:
      - Analog Emulator: "!include ./oqd-analog-emulator/mkdocs.yaml"
      - Trapped Ion Calculator: '!include ./oqd-trical/mkdocs.yaml'
  - Cloud: "!include ./oqd-cloud/mkdocs.yaml"
  - Compiler Infrastructure: "!include ./oqd-compiler-infrastructure/mkdocs.yaml"
  - Hardware:
      - OQD Processors: hardware/devices.md
      - OQD Modules: hardware/modules.md
      - About OQD Hardware: hardware/about-oqd.md
  - Utilities:
      - Data schemas: "!include ./oqd-dataschema/mkdocs.yaml"
  - About: about.md

theme:
  name: material
  logo: img/oqd-icon.png
  favicon: img/oqd-icon.png

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to light mode



  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.tooltips
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.prune
    - toc.follow

plugins:
  - monorepo:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths:
            - ./oqd-compiler-infrastructure/src
            - ./oqd-core/src
            - ./oqd-analog-emulator/src
            - ./oqd-cloud/src
            - ./oqd-trical/src
            - ./oqd-dataschema/src
          options:
            show_source: true
            show_root_heading: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_submodules: true
            docstring_style: "google"
            docstring_section_style: "table"
            show_signature: true
            show_signature_annotations: true
            signature_crossrefs: true
            separate_signature: false
            group_by_category: true
            members_order: "source"
          import:
            - https://docs.python.org/3/objects.inv
            - https://docs.pydantic.dev/latest/objects.inv
            - https://qutip.readthedocs.io/en/qutip-4.7.x/objects.inv
            - https://pandas.pydata.org/docs/objects.inv
            - https://matplotlib.org/stable/objects.inv
            - https://numpy.org/doc/stable/objects.inv
  - mkdocs-jupyter:
      ignore_h1_titles: True

markdown_extensions:
  - attr_list
  - toc:
      permalink: true
      toc_depth: 10

  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

  # for notes/admonitions
  - pymdownx.blocks.admonition
  - pymdownx.blocks.details
  - pymdownx.blocks.html
  - pymdownx.blocks.tab:
      alternate_style: true

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - pymdownx.arithmatex:
      generic: true

  - mdx_truly_sane_lists:
      nested_indent: 2
      truly_sane: True

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/headers.css
  - stylesheets/admonitions.css
  - stylesheets/brand.css
